# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StarbucksClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StarbucksClone
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'  
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'

  pod 'SideMenu'

  target 'StarbucksCloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StarbucksCloneUITests' do
    # Pods for testing
  end

end
